name: CI  pipeline

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install dependancy
        run: npm install

      - name: dependancy check
        run: npm audit --audit-level=high

      - name: run lint
        run: npx eslint .

      - name: run test
        run: npm install
