name: Node ENV CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  APP_NAME: GitHubActionsDemo
  PORT: 3000

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: npx eslint .

      - name: Run Application
        run: node app.js


  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test


  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Deployment Step
        run: echo "Application deployed successfully"
