name: CI  pipeline

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-letest 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install dependancy
        run: npm install

      - name: run test
        run: npm install  
